apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: amenezesrh-operators
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: amenezesrh